<?php

namespace AdminMiddleware\Providers;

use Dingo\Api\Routing\Router; 
use AdminMiddleware\Middleware\AdminAuthMiddleware;

class AdminServiceProvider extends \Illuminate\Support\ServiceProvider
{

    /**
     *
     */
    public function register()
    {
        $router = app('router');
        $router->aliasMiddleware('admin.auth', AdminAuthMiddleware::class);
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function boot()
    {
        $this->publishes([
            __DIR__.'/../config/adminMiddleware.php' => config_path('adminMiddleware.php')
        ], 'config');
    }
}
